# Generated by Django 5.0.1 on 2024-01-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
