# Generated by Django 5.0.1 on 2024-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ublood',
            field=models.CharField(default='A+', max_length=5),
            preserve_default=False,
        ),
    ]
